package com.mediaflow.core.model

/**
 * Represents a single download (pending, active or finished).
 *
 * Fields not yet available are optional or use safe default values. No fake
 * data is generated by the model itself.
 */
data class DownloadItem(
    val id: String,
    val sourceUrl: String,
    val title: String? = null,
    val fileName: String? = null,
    val mediaType: MediaType,
    val selectedFormat: MediaFormat? = null,
    val localUri: String? = null,
    val thumbnailUri: String? = null,
    val durationSeconds: Long? = null,
    /** 0..1 only when [isProgressKnown] is true; never a fabricated value. */
    val progress: Float = 0f,
    val isProgressKnown: Boolean = false,
    val downloadedBytes: Long = 0L,
    val totalBytes: Long? = null,
    val speedBytesPerSecond: Long = 0L,
    val status: DownloadStatus = DownloadStatus.IDLE,
    val errorMessage: String? = null,
    val createdAt: Long = 0L,
    val completedAt: Long? = null,
)
